spring:
  application:
    name: pet-love
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: pet-love
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration



server:
  port: 8090